export enum PRODUCTS_PATTERN {
    TEST = "TEST",
    GET = "GET_PRODUCT",
    GET_ALL = "GET_ALL_PRODUCTS",
    CREATE = "CREATE_PRODUCT",
    UPDATE = "UPDATE_PRODUCT",
    DELETE = "DELETE_PRODUCT",
}